### ISSUE TITLE
Iteration Plan for June 2019

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/nni#1142]
This plan captures our work in **June**. This is a 4 week iteration, and we will **ship** our June update in **in early July**. We'll continue work we started in the previous iteration, and we started to pick up items from our [roadmap](https://github.com/Microsoft/nni/wiki/Roadmap).

## Endgame
**June ~24~ 25**: Code freeze for the endgame
**July 1st**: Endgame done

The endgame details for this iteration are tracked in [June Endgame](https://github.com/microsoft/nni/issues/1161).

## Plan Items
Below is a summary of the top level plan items.

### Tuners and Assessors
- [x] Tuner Installation Improvements #858 @SparkSnail 
- [x] Oneshot example (ENAS, etc.) #1159 @Crysple 
- [x] Add GP Tuner and related doc #1191 @suiguoxin 

### Training Service
- Multiphase support: @chicm-ms 
   - [x] multiphase support PAI mode
   - [x] multiphase refactoring #1138 

### Web Portal & User Experience
- [x] trial compare #1062 @lvybriage 
- [x] Enhancement: ability to adjust rendering interval. #1106  @lvybriage 
- [x] Command to Delete Experiments. (risk on azure storage) #1123 @SparkSnail 
- [x] show intermediate results more friendly #536 @lvybriage 

### Bug Fixes 
- [x] Failed to connect to PAI http code:500 #1076 @demianzhang 
- [x] Validate file name in PAI platform #1164 @SparkSnail 
- [x] fix negative time number in local mode when trial time is short #1185 @LeonardoWang 
- [x] Trial's end time is less than start time in auto gbdt example #1182; fix negative time number in local mode when trial time is short #1185; owner: xupu/tester: jiangong.
- [x] hyper-parameter not shown correctly in WebUI when there is only one hyper parameter #1192 @lijiao // PR #1200 xuehui/chengmin
-----------------------
## Deferred Items
- Intermediate result @suiguoxin 
- [ ] Add NAS examples as NNI example #1158 @Crysple 
- [ ] Assign dedicated resources (such as GPU) to Tuner #874 @QuanluZhang 
- [ ] retrieve the values of the metrics in a programmatic way #868 @chicm-ms 
- [ ] UX (design only) for retry FAILED trial #1180 @lvybriage @yangou1988  
- [ ] Latest paper for NAS (AutoML blog/analysis) - #1160  @suiguoxin / xupu / @Crysple 
- _investigation_ - Model compression #876 - xupu
- [ ] (_Pending for evaluation results_) Add a parallel algorithm to improve the performance of TPE with large concurrency #1052 @Crysple
