### ISSUE TITLE
June 2019 Release Endgame Plan

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/nni#1161]
This is the endgame schedule for [June 2019 Iteration](https://github.com/microsoft/nni/issues/1142).
_last updated on 6/26/2019_

**Schedule** (this may change)
-----------------
- End game master: @leckie-chn 
**June ~24~ 26**: Code freeze for the endgame
**July 1st**: Endgame done
**July 1st**: Expected release date 

refer to may endgame: https://github.com/microsoft/nni/issues/1089

06/26 
- [X] Code freeze at 4pm UTC+8 
- [x] _(pending)_ Integration Test
- [x] Release branch v0.9
- [x] Build NNI test pypi package.
- [x] Build NNI test docker image for v0.9 release bug bash.

06/26 -07/01 Bug bash
----------------------
### Tuners and Assessors
- [x] Tuner Installation Improvements #858 owner: @SparkSnail /tester: @Crysple 
- [x]  Oneshot example (ENAS, etc.) #1159 owner: @Crysple /tester: @suiguoxin 
- [X]  Add GP Tuner and related doc #1191 owner: @suiguoxin /tester: @Crysple 

### Training Service
- [x] Multiphase support: owner: @chicm-ms /tester:@SparkSnail
   -  multiphase support PAI mode
   -  multiphase refactoring #1138 

### Web Portal & User Experience
- [x] trial compare #1062 owner: @lvybriage /tester: @chicm-ms 
- [x]  Enhancement: ability to adjust rendering interval. #1106  owner: @lvybriage /tester: @yangou1988 /@suiguoxin
- [x]  Command to Delete Experiments. (risk on azure storage) #1123 owner: @SparkSnail /tester: @squirrelsc 
- [x]  show intermediate results more friendly #536 owner: @lvybriage /tester: @QuanluZhang 

### Bug Fixes 
- [x]  Failed to connect to PAI http code:500 #1076 @demianzhang /tester: xupu
- [x]  Validate file name in PAI platform #1164 @SparkSnail /tester: xupu
- [x] Trial's end time is less than start time in auto gbdt example #1182; fix negative time number in local mode when trial time is short #1185; owner: xupu/tester: jiangong.
- [x] hyper-parameter not shown correctly in WebUI when there is only one hyper parameter #1192 @lijiao // PR #1200 xuehui/chengmin; tester: @suiguoxin 

----------------------

- [x] V0.9 release notes
- [x] Remind teams to verify issue status

Monday July 1st
- [x] Rebuild NNI v0.9 pypi package
- [x] Rebuild NNI v0.9 official docker image. 
- [x] Push NNI v0.9 official docker image to Dockerhub
- [x] Announce NNI v0.9 release.
