### ISSUE TITLE
(Dup by #1274) Iteration Plan for July 2019

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/nni#1215]
This plan captures our work in **July**. This is a 4 week iteration, and we will **ship** our July update in **in early August**. We'll continue work we started in the previous iteration, and we started to pick up items from our [roadmap](https://github.com/Microsoft/nni/wiki/Roadmap).

## Endgame
**July 29**: Code freeze for the endgame
**Aug 5**: Endgame done
Release manager: @suiguoxin

The endgame details for this iteration are tracked in [July Endgame](to be created).

-----------------------
## Deferred Items from last sprint.
- [ ] Add NAS examples as NNI example #1158 @Crysple 
- [ ] Assign dedicated resources (such as GPU) to Tuner #874 @QuanluZhang 
- [ ] Latest paper for NAS (AutoML blog/analysis) - #1160  @suiguoxin / xupu / @Crysple 
- _investigation_ - Model compression #876 - xupu
- [ ] (_Pending for evaluation results_) Add a parallel algorithm to improve the performance of TPE with large concurrency #1052 @Crysple 
-----------------------

## Plan Items
- Intermediate result @suiguoxin 
- [ ] retrieve the values of the metrics in a programmatic way #868 @chicm-ms 
- [ ] UX (design only) for retry FAILED trial #1180 @lvybriage @yangou1988  
- [ ] support multiphase for hyperband PR #1257 @quanluzhang

Below is a summary of the top level plan items.

### Tuners and Assessors
- [ ] Auto-Feature generator & selection @baomengjiao @xuehui1991 
- _design auto feature interface_
- _random tuner or beam search tuner_
- _pakdd example_

### Training Service
to be added
### Web Portal & User Experience
to be added

### Bug Fixes 
to be added

**Comment by scarlett2018** [comment]
will track in #1274
