### ISSUE TITLE
Iteration Plan for July 2019

### ISSUE THREAD

**Issue by suiguoxin** [microsoft/nni#1274]
This plan captures our work in **July**. This is a 4 week iteration, and we will **ship** our July update in in **early August**. We'll continue work we started in the previous iteration, and we started to pick up items from our [roadmap](https://github.com/Microsoft/nni/wiki/Roadmap).

## Endgame
**Aug 5**: Code freeze for the endgame
**Aug 12**: Endgame done
Release manager: @suiguoxin

The endgame details for this iteration are tracked in [July Endgame](to be created).

#### 
-  [x] yarn.lock @liuzhe-lz #1412
-  [x] Add NAS examples as NNI example #1158 @QuanluZhang 
-  [x] Add blogs of popular NAS paper #1160 

### Docs, Blogs, Samples, Articles
- [x] Update NNI Introduction Board #1270 # 1313 @rabbit008 
- [x] Add a document similar to naming SupportTrainingService.md #1370 @rabbit008 @SparkSnail 

## Plan Items
-  [x] Unify nas searchspace #1393 @Crysple 
-  [x] (check )SMAC don't support quniform type? #1136 @QuanluZhang  
-  [x] retrieve the values of the metrics in a programmatic way #868 @chicm-ms 
-  [x] Add a parallel algorithm to improve the performance of TPE with large concurrency #1052 [need an option to turn on/off parallel] @xuehui1991 @Crysple 
-  [x] support multiphase for hyperband PR #1257 @QuanluZhang

## Tuners and Assessors
-  [x] Auto-Feature generator & selection #877 @baomengjiao @xuehui1991
    -  [x] design auto feature interface
    -  [x] random tuner or beam search tuner
    -  [x] pakdd example

## Training Service
- [x] NNI doesn't support private docker registry #755 @sparksnail
- [x] get_experiment_id, get_trial_id python API @suiguoxin

## Engineering Improvements
-  [x] Python wrapper for rest api #1318(pr) @chicm-ms  (need review)
-  [x] sometimes CUDA_VISIBLE_DEVICES="-1" is not wanted #1365 @SparkSnail 
-  [x] Remove outputDir and dataDir configuration in PAI mode #1342 @SparkSnail 
-  [x] Copy codeDir to logDir when create trial on Kubeflow mode #1224 @SparkSnail 

## Web Portal & User Experience
- [x] Can nni show the best metric curve during search progress in WebUI? #1218 @lvybriage (modify)
- [x] Some improvements in webui #1210 @lvybriage 
    - trial progress(intermediate results count) : as a customized column
- [x] webui not support search parameters value #1208 @lvybriage
- [x] WebUI上显示的metric动态调整下画图的区间 #1360 @lvybriage
- [x] Add a detailed documentation link to the nnictl command in the command prompt. #1260 @SparkSnail 
- [x] webui nav #1230 @lvybriage 
- [x] UX improvement for showing Error log #1173 @yangou1988 @Ivybriage
- [x] slow rendering of webui #590 @LeonardoWang 

## Docs, Blogs, Samples, Articles
- [x] multi phase doc improvement #1233 @chicm-ms #pull 1242  
- [x] Update the docs structure #1231 @xuehui1991 pr to review

## Bug Fixes
- [x] script for auto-complete @liuzhe-lz 
- [x] Fix pipeline issue that it only check exit code of last command in a script. #1417 @chicm-ms 
- [x] quniform fors tuners #1377 @suiguoxin 
- [x] 'quniform' has different meaning beween GridSearch and other tuner. #1335 @suiguoxin 
- [x] "nnictl experiment list" give the status of a "RUNNING" experiment as "INITIALIZED" @SparkSnail 
- [x] SMAC cannot be installed if nni is installed in dev mode #1376 @SparkSnail 
- [x] 404 links in 0.9 release #1236 @leckie-chn
- [x] The filter button of the intermediate result cannot be clicked #1263 @lvybriage
- [x] API "/api/v1/nni/trial-jobs/xxx" doesn't show a trial's all parameters in multiphase experiment #1258 @chicm-ms 
- [x] Succeeded trial doesn't have final result but webui show ×××(FINAL) #1207 @chicm-ms 
- [x] IT for nnictl stop @Crysple #1298 
- [x] fix security warning @chicm-ms 
- [x] Hyper-parameter page broken #1332 @lvybriage
- [x] Run flake8 tests to find Python syntax errors and undefined names #1217
