### ISSUE TITLE
July 2019 Release Endgame Plan

### ISSUE THREAD

**Issue by suiguoxin** [microsoft/nni#1410]
This is the endgame schedule for July 2019 Iteration.
last updated on 8/4/2019

End game master: @suiguoxin
Aug 6: Code freeze for the endgame
Aug 12: Endgame done
Aug 12: Expected release date
release track @scarlett2018 
refer to June endgame: #1161

08/06
- [x] Code freeze at 4pm UTC+8 
- [x] Cut branch v1.0
- [x] Build NNI test pypi package.
- [x] Build NNI test docker image for v1.0 release bug bash.

### 08/12 Bug bash Round 2
- [x] UT fail
- [x] randint @ultmaster  tester @suiguoxin
- [x] quniform in metis   tester
- [x] smac support quniform only when q=1 @leckie-chn 
- [x] Failed trials show a huge negative duration on macOS #1416 tester @QuanluZhang 
- [x] Set TPE classArgs as optional #1436 @SparkSnail  tester @suiguoxin 
- [x] Hotfix for /tmp/nni permission problem #1439 @liuzhe-lz  tester @LeonardoWang 
- [x] fix bugs, sort, concurrency, multi #1451 tester @liuzhe-lz  @LeonardoWang 
- [x] Add a parallel algorithm to improve the performance of TPE with large concurrency #1052  [need an option to turn on/off parallel] @xuehui1991 @Crysple  tester @chi song
- [x] NNI doesn't support private docker registry #755 @sparksnail tester @QuanluZhang 
- [x] broken link tester @QuanluZhang 

----------------------
#### 
- [x] yarn.lock security alert @liuzhe-lz #1412 tester @lvybriage 
- [x] Add NAS examples as NNI example #1158 @QuanluZhang
- [x] Update filter description and fix typo
- [x] IT fail @SparkSnail 
- [x] nnictl stop --all @SparkSnail 
- [ ] It cannot work with nni-0.9 version but work with nni-0.7 version # issues1353 #pr1418
- [x] randint @ultmaster  @suiguoxin 
- [x] quniform in metis   @suiguoxin 
- [x] Failed trials show a huge negative duration on macOS #1416
- [x] Set TPE classArgs as optional #1436 @SparkSnail 
new pr: 
- [x]Hotfix for /tmp/nni permission problem #1439 @liuzhe-lz 
- [x] smac support quniform only when q=1 @suiguoxin  tester @leckie-chn 

### Docs, Blogs, Samples, Articles
- [x] Update NNI Introduction Board #1270 # 1313 @rabbit008 
- [x] Add a document similar to naming SupportTrainingService.md #1370 @rabbit008 @SparkSnail 

## Plan Items
-  [x] Unify nas searchspace #1393 @Crysple  tester @ultmaster 
-  [x] retrieve the values of the metrics in a programmatic way #868 @chicm-ms tester @suiguoxin
-  [x] Add a parallel algorithm to improve the performance of TPE with large concurrency #1052  [need an option to turn on/off parallel] @xuehui1991 @Crysple  tester @chi song
-  [x] support multiphase for hyperband PR #1257 @QuanluZhang tester @chicm-ms 

## Tuners and Assessors
-  [x] Auto-Feature generator & selection #877 @baomengjiao @xuehui1991 tester @leckie-chn 
    -  [ ] design auto feature interface
    -  [ ] random tuner or beam search tuner
    -  [ ] pakdd example

## Training Service
- [x] NNI doesn't support private docker registry #755 @sparksnail tester @QuanluZhang 
- [x] get_experiment_id, get_trial_id python API @suiguoxin tester @liuzhe-lz 

## Engineering Improvements
-  [x] Python wrapper for rest api #1318(pr) @chicm-ms  tester @suiguoxin 
-  [x] sometimes CUDA_VISIBLE_DEVICES="-1" is not wanted #1365 @SparkSnail tester @QuanluZhang 
-  [x] Remove outputDir and dataDir configuration in PAI mode #1342 @SparkSnail
-  [x] improvement: not Copy codeDir to logDir when create trial on Kubeflow mode #1224 @SparkSnail tester @SparkSnail 

## Web Portal & User Experience
- [x] Can nni show the best metric curve during search progress in WebUI? #1218 @lvybriage (modify) tester @liuzhe-lz @LeonardoWang 
- [x] Some improvements in webui #1210 @lvybriage  tester @liuzhe-lz @LeonardoWang 
    - trial progress(intermediate results count) : as a customized column
- [x] webui not support search parameters value #1208 @lvybriage tester @liuzhe-lz @LeonardoWang 
- [x] WebUI上显示的metric动态调整下画图的区间 #1360 @lvybriage tester @liuzhe-lz @LeonardoWang 
- [x] Add a detailed documentation link to the nnictl command in the command prompt. #1260 @SparkSnail tester @suiguoxin 
- [x] webui nav #1230 @lvybriage tester @liuzhe-lz @LeonardoWang 
- [x] UX improvement for showing Error log #1173 @yangou1988 @Ivybriage tester @liuzhe-lz @LeonardoWang 

## Docs, Blogs, Samples, Articles
- [x] Broken link check (build log) tester @leckie-chn  @QuanluZhang @ultmaster  tester @QuanluZhang 
- [x] multi phase doc improvement #1233 @chicm-ms #pull 1242  
- [x] Update the docs structure #1231 @xuehui1991 

## Bug Fixes
- [x] script for auto-complete @liuzhe-lz  tester @SparkSnail 
- [x] Fix pipeline issue that it only check exit code of last command in a script. #1417 @chicm-ms tester @SparkSnail 
- [x] quniform fors tuners #1377 @suiguoxin  tester @ultmaster 
- [x] 'quniform' has different meaning beween GridSearch and other tuner. #1335 @suiguoxin tester @ultmaster  
- [x] "nnictl experiment list" give the status of a "RUNNING" experiment as "INITIALIZED" @SparkSnail  tester @QuanluZhang 
- [x] SMAC cannot be installed if nni is installed in dev mode #1376 @SparkSnail tester @suiguoxin 
- [x] 404 links in 0.9 release #1236 @leckie-chn tester @rabbit008 
- [x] The filter button of the intermediate result cannot be clicked #1263 @lvybriage tester @liuzhe-lz @LeonardoWang 
- [x] API "/api/v1/nni/trial-jobs/xxx" doesn't show a trial's all parameters in multiphase experiment #1258 @chicm-ms tester @lvybriage  
- [x] Succeeded trial doesn't have final result but webui show ×××(FINAL) #1207 @chicm-ms tester @liuzhe-lz @LeonardoWang 
- [x] IT for nnictl stop @Crysple #1298 
- [x] fix security warning @chicm-ms 
- [x] Hyper-parameter page broken #1332 @lvybriage tester @liuzhe-lz @LeonardoWang 
- [x] Run flake8 tests to find Python syntax errors and undefined names #1217
