### ISSUE TITLE
Iteration Plan for release in Mar

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/nni#2079]
Extending this short iteration to a regular iteration for Feb-Mar.
**Release Manager**: @liuzhe-lz 
**Code freeze date**:  ~3/2 3/26 (Wed)~ 3/27
**End Game Issue**: #2132 2132
**Target release date**: ~3/6~ 3/31 (Tue)

---
### Code completed 
**DLTS/DLWorkspace integration**
- [x] Integration with DLWS  PR #1945 @QuanluZhang, @Gerhut;
    - ~support pause status @chicm-ms  PR #2090  (review @liuzhe-lz @QuanluZhang )~
    - ~~support pause status on webui~~ @lvybriage (pending)
    - [x] fix IT fail @Gerhut
    - [x] current log path @Gerhut

- [x] model compression examples refactor @chicm-ms  / reviewer: @Cjkkkk @QuanluZhang  PR #2099
   - [x] prepare GPU vm for pipeline (1.14), migrate remote docker to the GPU vm @SparkSnail  
- [x] speedup example refactor @QuanluZhang 
- [x] refactor the logic of applying mask file @QuanluZhang
- [x] compression framework refactor @Cjkkkk 
- [x] validation of configuration passed to compression algorithms @chicm-ms 

### In progress
**NAS**
- [x] NAS visualization @ultmaster / Reviewer: @lvybriage @QuanluZhang @SparkSnail  PR #2085 
- [x] NAS installation @SparkSnail  (3/23)

**New Algo**
- [x] support HPO algo - PBT #1470  @RayMeng8 (draft pr #2139, debugging, a pr ready in next week)

**AutoNLP**
- [x] AutoNLP @QuanluZhang 
     - [x] search algo @ultmaster
     - [x] retrain / Add evaluation script for TextNAS #2204 @pkuyym pr #2220 

**IT/UT**
- [x] add IT/UT @chicm-ms  PR #2190  need review
    - [x] refactor framework (eta: wed)
    - [x] resume experiment
    - [x] trial uses dict metric
    - [x] experiment view, experiment foreground
    - [x] IT for NAS
    - [x] IT for model speedup
    - [x] replace pai IT with new ones @SparkSnail  PR #2092  (debugging)
    - [x] IT failure (smac) @chicm-ms 
-----
## Bug Fix
- [x] web ui bug: issue #2087  @lvybriage  PR # 2162  waiting review
- [x] launcher exception: issue #2080 PR #2086 @SparkSnail  review: @chicm-ms @QuanluZhang 
- [x] webui supports NaN/Infinite @lvybriage  PR #2183  review: @chicm-ms @liuzhe-lz 

-----
##Other candidates
- [x] remove deprecated nas examples @QuanluZhang @ultmaster 
- [x] customized homepage for sphinx doc build (before code freeze) @leckie-chn @lvybriage 
- ~PT test @ultmaster (择吉日)~

---------------------
## Deferred Items
**TF 2.0** @liuzhe-lz #2127 
  - [ ] structure codes + ENAS example as first pr, eta ~3/18~ 3/20 #2115
  - [ ] Examples - Rewrite TFv1 example trials with TFv2
  - [ ] NAS SDK and 1-2 examples

- [ ] bug - clone fail #1985
- [ ] clean issues assigned to each member - 121 issues in total by 2/21
- [ ] lottery ticket pruner, add exporting winning ticket @QuanluZhang

**Comment by scarlett2018** [comment]
left work is tracking in endgame ticket.
