### ISSUE TITLE
Iteration Plan for May 2020

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/nni#2301]
Extending this short iteration to a regular iteration for Feb-Mar.
**Release Manager**: @SparkSnail 
**Code freeze date**:  to be decided
**End Game Issue**: to be created
**Target release date**: to be decided

---
## Deferred from last iteration
- [ ] TF 2.0 https://github.com/microsoft/nni/issues/2127 @liuzhe-lz 
   --- Using NNI NAS interface with keras/tf.keras #1737
   --- TensorFlow 2.0 API change #1614
- [ ] PBT left work and improvement @quanluzhang (issue to be created)
- [ ] IT left work #2290 @chicm-ms 
- [ ] use new interface to implement the removed NAS examples @QuanluZhang (issue to be created)
- [ ] finalize the homepage migration to readthedoc (refine layout and add breaklink check) @leckie-chn (issue to be created)
- [ ] lottery ticket pruner, add exporting winning ticket @chicm-ms  (issue to be created)
- [ ] Show trial error message #1541 @chicm-ms 

## Top in our mind (as candidates)
[1] Internal scenario based usage
[2] External feedback ==> clustering ==> usage and scenario
~[3] TF 2.0~
[4] 开发文档
[5] register user's tuner as build-in tuner
[6] + "--version" for SDK version
[7] 针对Data的automation, 针对data的augmentation (image and NLP) 
[8] NAS优化相关的API的改动，增加final architecture的可读性，可视化和其他用户体验
[9] SimpleTuner https://github.com/microsoft/nni/issues/2151
[10] PBD trial fail and on trial end
[11] 更新一下PAI merge的方式
[12] 优化Storage方式，share code storage among trials in an experiements
[13] WebUI improvement  and bugs backlog
[14] 精进 Model compression 实现 for real workload like face detection
[15] 实际对model的speedup (collaberate with Yuxin's team)
[16] Model compression PyTorch 1.4支持, utility codes的merge
[17] Yuge's current NAS algo adding to NNI as example
[18] AzureML as a training service
[19] Windows as remote training node (Chi)
[20] Feature engineering/selection (L1 ranker) TPOT (http://automl.info/tpot/)

## Other backlogs  (as candidates)
https://github.com/microsoft/nni/issues/1917

## Planned Items
To be updated
