### ISSUE TITLE
NNI Student Program 2020 Planning Discussion

### ISSUE THREAD

**Issue by JSong-Jia** [microsoft/nni#2382]
# NNI Student Program 2020

## Key Timeline
~**Program Kickoff**: 04.08~
~**Webnair**: 04.16~
~**Registration Confirmation & Task Release**: 04.27~
**Submission Date**: 05.10-06.14

## Task 1.1 (HPO Sample)
~Submission deadline:  05.10~

## Task 1.2 (HPO+NAS)
~Submission deadline for Task 1.2_HPO:  05.20~
~Submission deadline for Task 1.2_NAS: 06.14~

## Task 1.3 (Feature Engineering)
~Submission deadline for Task 1.3_Sample:  05.10~
~Submission deadline for Task 1.2_Test: 06.14~

## Task 1.4 (Self-registration task)
~Submission deadline for Planning Report:  05.10~
~Submission deadline for Mid-term Report: 05.31~
~Submission deadline for Final Report: 06.14~

## Detailed Task Description
https://github.com/JSong-Jia/NNI-Student-Program-2020

**Comment by RudieLi** [comment]
#  NNI Student Program 2020
##  Key Timeline
- [x] Program Kickoff: 04.08
- [x] Webnair: 04.16
- [x] Registration Confirmation & Task Release: 04.27
- [x] Submission Date: 05.10-06.14
## Task 1.1 (HPO Sample)
- [x] Submission deadline:  05.10
## Task 1.2 (HPO+NAS)
- [x] Submission deadline for Task 1.2_HPO:  05.20
- [x] Submission deadline for Task 1.2_NAS: 06.14
## Task 1.3 (Feature Engineering)
- [x] Submission deadline for Task 1.3_Sample:  05.10
- [x] Submission deadline for Task 1.2_Test: 06.14
## Task 1.4 (Self-registration task)
- [x] Submission deadline for Planning Report:  05.10
- [x] Submission deadline for Mid-term Report: 05.31
- [x] Submission deadline for Final Report: 06.14
## Detailed Task Description
> https://github.com/JSong-Jia/NNI-Student-Program-2020
