### ISSUE TITLE
Bug bash for release

### ISSUE THREAD

**Issue by SparkSnail** [microsoft/nni#2464]
v1.6 bug bash

**General Supports Updates**
- [ ] TF 2.0 ENAS https://github.com/microsoft/nni/issues/2127 @ultmaster  (fixing import error)
- [ ] 100W IPC limitation @SparkSnail (fixing bug)
- [ ] share code storage among trials in an experiements @liuzhe-lz 
- [x] fix dev install @leckie-chn 
- [ ] `__version__` for SDK version @chicm-ms (need to fix issue)
- [x] windows dev install @leckie-chn 
- [ ] support windows as remote machine @SparkSnail 

**Web UI** @chicm-ms 
- [ ] finalize the homepage migration to readthedoc (#2483 need to merge code)
    ----refine layout
- [x] Show trial error message #2424  
- [x] Refactor overview top trials: 
related issue: https://github.com/microsoft/nni/issues/2007  https://github.com/microsoft/nni/issues/2010

**HPO Updates**
- [ ] PBT left work and improvement @colorjam (need to fix issue)

**NAS Updates**

- [x] improvement NAS API, add readability, improve user experience @liuzhe-lz 

**Model Compression Updates**
- [x] Model compression PyTorch 1.4 support, utility codes merge #2310 @colorjam (need to fix issue)

**Training Service Updates** @ultmaster 
- [x] support pai multiphase  
- [x] update pai yaml merge #2309

**Comment by kvartet** [comment]
closed as it is overdue.
