### ISSUE TITLE
June release end game

### ISSUE THREAD

**Issue by chicm-ms** [microsoft/nni#2621]
## Release 1.7
- Release manager: @chicm-ms
- Code freeze date: 7.1
- Demo and retrospective date: 7.3
- Release and next iteration plan date: 7.8
-----
## Planned Items
- [x] use new interface to implement the removed NAS examples @QuanluZhang #2311  test: @tabVersion 
- [x] NASUI @ultmaster  test: @tabVersion 
    --- NASUI bugs, UT 
    issue:  saw a warning message on web UI: graph too large.  ( no fix)
- [x] Add Support for NAS Open Benchmarks #2506 @ultmaster   test: @Jun Wei  Sun 
       issue: 1. generated file in docker can not be deleted outside.
- [x] Guidelines to handle large files in codeDir #2364  @ultmaster   test:  @Lin Bin
      tested file size,    not tested:  file numbers
- [x] merge parameter utils #2437  TBD @ultmaster  PR #2540  test: @chicm-ms 
- [x] WebUI @lvybriage 
    - [x] Enhancement to trial duration display https://github.com/microsoft/nni/issues/1489  PR #2523  @colorjam 
    - [x] during and intermediate results pictures update, issue to create issue.   6/5 #2531 @Lijiaoa 
    - [x] Support nested experiment more friendly https://github.com/microsoft/nni/issues/2513  ~6/11~  6/15  pr #2554 @QuanluZhang 
           issues:  to fix,   PR #2635 
    - [x] Hyper-parameter   https://github.com/Microsoft/nni/issues/1483   one week  6/19, pr 6/22  #2586 @QuanluZhang 
    - [x] minior webui  table style issues by @QuanluZhang  6/17  PR #2571 @QuanluZhang 
- [x] update pai storage, issue #2331  @SparkSnail (PAI 1.01 released)  PR #2536   test: @QuanluZhang 
     feedback: provide log info in nnimanager.log/webui for large file while uploading...    @SparkSnail : issue/pr
- [x] AML integration  @SparkSnail   test: @Jun Wei Sun
      issue: 
            1. conda is required in docker  if user docker not specified.   to fix
            2. version check  caused by manually built image
            3. document picture  not same as external users' azure UI.   to fix.
      PR #2633  review: chicm-ms
- [x] register user's tuner as build-in tuner (@chicm-ms )( 5.15 )  (#2439  ) ,  test: @ultmaster 
      doc PR: #2628 
- [x] finalize the homepage migration to readthedoc @leckie-chn #2312 (4.24)    test:  @chicm-ms 
- [x] Reuse OpenPAI jobs to run multiple trials  #2521    test:  @SparkSnail 
      issue:  failed to submit job if nniManagerIP is not set.    to fix
- [x] Add OpEvo example #PR 2549    test: @QuanluZhang 
     to update doc:  add an picture

### Model compression TODOs:
- [x] 1. Model speedup support resnet ( concat, add, conv2d group > 1)  ~6/10~  6/17 @zheng-ningxin   test: @chicm-ms 
        to do next release:  inception,  densenet
- [x] 2. Fix bug for model graph with shared nn.Module  #2485 @zheng-ningxin  test: @chicm-ms 
- [x] 4. Support more pruning algorithms  #2490  @suiguoxin  test: @colorjam 
      issue:  to fix example model next release. 
- [x] 5. Model sensitivity analysis tool #2435  @zheng-ningxin  test: @chicm-ms 
- [x] lottery ticket pruner, add exporting winning ticket @chicm-ms  PR #2559  @colorjam 
- [x] flops calculation for model compression and NAS @colorjam 6/8 PR #2535 to schedule a meeting to discuss PR #2535   test: @ultmaster
      issue:   thop warning message, to fix 

## Bugs
- [ ] nodejs OOM when `make build` #2475  (@liuzhe-lz )  PR submitted  test: @chicm-ms
      how to reproduce:  ask niyan  

TODO:
  demo at feature code freeze  from next release.   record demo video

**Comment by scarlett2018** [comment]
Released: https://github.com/microsoft/nni/releases/tag/v1.7
