### ISSUE TITLE
September Iteration Plan

### ISSUE THREAD

**Issue by QuanluZhang** [microsoft/nni#2841]
This is the draft plan for the upcoming iteration in September, it's a 4 weeks iteration.

## Release Plan for v1.9
- Release manager: @QuanluZhang 
- Feature freeze date: ~9/22~ 9/23
- Code freeze and demo date: ~9/29~ 10/9
- WebUI specific: 10/12
- Retrospective date: 10/13
- Release and next iteration plan date: ~10/19~ ~10/20~ 10/21
-----
Let's try to adopt the legend of annotations:

Mark | Description
------|--------------
🏃‍♂️ | work in progress
👪 | work under review
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue / pull request reference
🔵 | more investigation and survey required
⚫ | under discussion within the team
⬛ | a large work item, larger than one iteration

### NAS
- [x] Support more tuning algorithms for classic NAS (regularized evolution) @tabVersion 
    - [x] regularized evolution,  9/22, pr #2802 , reviewer @ultmaster @chicm-ms @QuanluZhang 
- [x] NAS bench 201 in search space zoo @tabVersion pr #2766 reviewer: @ultmaster @QuanluZhang 

### Model Compression
- [x] Model compression doc refactor @chicm-ms (survey) 9/22, pr #2919 , reviewer @QuanluZhang @colorjam 
- [x] Quantization doc refactor, algorithm and framework review, support post-train quantization speedup @linbinskn 
    ~1. review supported quantize algorithms, 9/7: Dorefa fix, reproduction of supported quantization algorithms~
    - [x] discussion of current quantization framework 9/7, conclusion: no need to refactor (done).
    - [x] update quantization doc 9/14
    - [x] support bias in quantization algorithms, pr #2914 , reviewer: @chicm-ms @QuanluZhang 

- [x] AMC improvements @chicm-ms 
    - [x] support resnet: ~9/9~ ~9/11~ ~9/16~ 9/17, pr #2876 , reviewer: @QuanluZhang @zheng-ningxin 
               Remove the restriction of kernel size must be 1x1,  support larger kernel size.
               Integrate NNI's automatic dependency extraction instead of hard coded dependency.
               Use NNI's speedup framework in AMC to replace the existing one.
    - [x] use paper reproduce parameters as default parameters for the example, pr #2906, reviewer: @QuanluZhang @zheng-ningxin 
- [x] flops counter refactor, pr ready #2795  @colorjam reviewer: @chicm-ms @liuzhe-lz 
- [x] Update TF model compression  @liuzhe-lz
    - [x] support sequential  9/9 , pr #2887 , reviewer: @chicm-ms @QuanluZhang 
- [x] constraint-aware pruner @zheng-ningxin pr #2657 reviewer: @chicm-ms @QuanluZhang 

### WebUI & NASUI
- [x] Support visualization and management of multiple experiments on WebUI @yangou1988 @Lijiaoa @sharonxingyufan 
    - [x] design, 2 days, done
    - [x] improve UI @Lijiaoa ~9/18~
        - [x] new overview page 9/22, pr #2924 reviewer: @ultmaster @colorjam @liuzhe-lz 
    - [x] upgrade node and yarn 9/16 @ultmaster pr #2894 
    - [x] upgrade Fabric UI @Lijiaoa 9/7 pr ready #2873 , reviewer: @liuzhe-lz @ultmaster 
    - [x] ESlint @Lijiaoa pr #2744 reviewer: @ultmaster @liuzhe-lz 
- [x] improvement of tensorboard support @yangou1988 
    - [x] WebUI design @yangou1988 @sharonxingyufan 9/14
- [x] Add/Remove columns in hyper-parameter chart and trial details table and Refactor trial details table (click event) @ultmaster ~9/18~ ~9/20~ ~9/23~ 10/6 pr #2900 
    - [x] choose trial will be broken when click table pagination @ultmaster  @Lijiaoa ~9/20~ ~9/23~ 10/6
- [x] JSON format utility beautify on WebUI @liuzhe-lz 9/3  PR #2863 reviewer: @Lijiaoa @ultmaster 

### nnictl
- [x] support adding description to experiment to make users easily identify a certain experiment @SparkSnail  ~9/9~ ~9/18~ ~9/23~ ~9/25~ 9/27 (design)
    - [ ] need followup discussion and work items
- [x] Nnictl auto-complete @JunweiSUN 9/7 pr ready, #2857 reviewer: @liuzhe-lz @SparkSnail 
- [ ] reconsider the name of nnicli, update doc, NNI rest python client @scarlett2018 

### training service
- [x] Configure python environment in remote mode @J-shang ~9/7~ 9/8, pr #2875 , reviewer: @SparkSnail @chicm-ms , related issue #2366 
- [x] adapt remote training service to the reuse framework @SparkSnail 9/22, #2923 , reviewer: @chicm-ms @squirrelsc @tabVersion 
- [x] aml mode under Windows @J-shang pr #2882 , reviewer: @SparkSnail @liuzhe-lz 

### UT & IT
- [x] Add IT cases: @J-shang 
    - [x] Import/export 9/9, pr #2878 , reviewer: @chicm-ms @ultmaster 
    - [x] User installed builtin tuner, pr ready, reviewer: @chicm-ms @liuzhe-lz 
- [x] Nnictl UT @SparkSnail 9/18, pr #2912 , reviewer: @chicm-ms @ultmaster 

### Documentation
- [ ] table rendering issue in Chinese doc @tabVersion  @JunweiSUN 
- [ ] fix readthedocs warning issue @tabVersion  @JunweiSUN 
- [x] fix readthedocs build error @ultmaster 9/18
- [ ] doc solution for restful apis, use sphinx-js @tabVersion  9/22 discussion done, 9/30
    - [ ] upgrade sphinx @tabVersion 9/30

### Others
- [x] fix Dependabot alerts @chicm-ms 9/27

### bug fix
- [x] Bug fix of naïve evolution tuner @colorjam , 9/8, discussion done, pr #2695 , reviewer: @QuanluZhang @tabVersion @chicm-ms 
- [x] "WARNING (nni.protocol) IPC pipeline not exists, maybe you are importing tuner/assessor from trial code?" @liuzhe-lz 1 day  PR: #2864 , reviewer: @chicm-ms @SparkSnail 
- [x] experiment save/load: search space issue @SparkSnail 9/11 pr #2886 reviewer: @ultmaster @chicm-ms 
- [x] experiment import bug @J-shang 9/9, pr, reviewer: @QuanluZhang @ultmaster 
- [x] annotation in remote mode, python 3.8 ast update issue, @J-shang pr #2881 @liuzhe-lz @QuanluZhang 

### To be discussed
- [x] review nnictl metadata management; experiment resume and save/load @SparkSnail @QuanluZhang , ~before 9/11~ 9/16, 9/23 review meeting

================

### NAS
- [x] regularized evolution, tester: @ultmaster 
- [x] NAS bench 201 in search space zoo, tester: @ultmaster 

### Model Compression
- [x] Model compression doc refactor, tester: @QuanluZhang  
    - [x] update quantization doc 9/14
- [x] support bias in quantization algorithms, tester: @chicm-ms 

- [x] AMC improvements tester: @colorjam 
    - [x] support resnet: pr #2876 , 
               Remove the restriction of kernel size must be 1x1,  support larger kernel size.
               Integrate NNI's automatic dependency extraction instead of hard coded dependency.
               Use NNI's speedup framework in AMC to replace the existing one.
    - [x] use paper reproduce parameters as default parameters for the example, pr #2906, 
- [x] flops counter refactor, tester: @chicm-ms  
- [x] support sequential  tester: @chicm-ms  
- [x] constraint-aware pruner, tester: @chicm-ms 

### WebUI & NASUI 
- [ ] new overview page, tester: @QuanluZhang 
- [x] Add/Remove columns in hyper-parameter chart and trial details table and Refactor trial details table (click event) tester: @SparkSnail 
- [x] JSON format utility beautify on WebUI tester: @Lijiaoa 

### nnictl
- [x] Nnictl auto-complete, tester: @liuzhe-lz 
- [ ] reconsider the name of nnicli, update doc, NNI rest python client @scarlett2018 

### training service
- [x] Configure python environment in remote mode, tester: @SparkSnail 
- [x] adapt remote training service to the reuse framework, tester: @J-shang 
- [x] aml mode under Windows, tester: @QuanluZhang 

### Documentation
- [ ] table rendering issue in Chinese doc @tabVersion  @JunweiSUN 
- [ ] fix readthedocs warning issue @tabVersion  @JunweiSUN 
- [ ] fix readthedocs build error, tester: @tabVersion 
- [ ] doc solution for restful apis, use sphinx-js @tabVersion  9/22 discussion done, 9/30
    - [ ] upgrade sphinx @tabVersion 9/30

### 🐛 bug fix
- [x] Bug fix of naïve evolution tuner, tester: @J-shang 
- [x] "WARNING (nni.protocol) IPC pipeline not exists, maybe you are importing tuner/assessor from trial code?", tester: @J-shang 
- [x] experiment save/load: search space issue, tester: @ultmaster 
- [x] experiment import bug, tester: @QuanluZhang 
- [x] annotation in remote mode, python 3.8 ast update issue, tester: @liuzhe-lz
