### ISSUE TITLE
NNI 2021 August~September Iteration Planning

### ISSUE THREAD

**Issue by QuanluZhang** [microsoft/nni#3986]
This is the plan for the iteration in August~September Iteration, it's a 6 weeks iteration.

# Release Plan for stableness release and use case support
- Release manager: @acured 
- Feature freeze date: ~Sept 9~ Sep 16
- Code freeze and demo date: ~Sept 16~ ~Sep 23~ ~Sep 28~ Oct 9
- Branch cut and next release planning date: ~Sept 23~ ~Sep 30~ Oct 13
- Bugbash - Oct 22
- Release date: ~Sept 27~ ~Oct 8~ ~Oct 9~ ~Oct 18~ Oct 25

### NAS
- [ ] (need review) fix benchmark @ultmaster 
  - [x] unify architecture format. Aug 20 #4090
  - [x] provide simple API for query. Aug 20 #4090
  - [ ] support benchmark end2end (test strategies' performance) #4205 
- [ ] support serialization @ultmaster #4172 
- [x] review and improve nas tests stage 1 @ultmaster. ~Aug 20~ Aug 31 #4097 
- [x] improve quick start (notebook) @QuanluZhang.  ~Aug 12~ ~Aug 17~ Aug 20 PR #4094 
  - [x] replace example, update mnist example.  ~Aug 27~ Sep 1
- [ ] examples for image classification, object detection, audio (show reasonably good performance)
  - [ ] transformer @skeletondyh ~Aug 31~ 
    - [x] investigate search space and common models and chose one to start.
    - [x] review meeting for investigate.  Sep 1
    - [x] implement NAS. Sep 8
    - [x] review meeting for result(demo). ~Sep 10~ ~Sep 15~ ~Sep 17~ Sep18
    - [ ] improvement and PR(code and doc) Sep 27 #4222 
- [x] deal with pytorch lightning onnx error for NAS visualization @ultmaster 

### Model Compression
- [ ] support compression v2 @J-shang Aug 20 #3917 #4074 #4089 #4116 #4178
  - [ ] tests #4125
  - [ ]  (bug bash)doc tutorial
- [ ] support per-channel quantization #4137 
- [ ] end2end examples for image classification, object detection, audio, transformer (show reasonably good performance)
  - [x] image classification (MobileNet) @xiaowu0162 ~Aug 18~ Aug 30 #4102 
    - [x] investigate model compression paper and try to compress model by NNI.
    - [x] review meeting for investigate and NNI result(demo).
    - [x] compare with other opensource compression tools.
    - [x] review meeting for comparing results.
    - [x] improvement and PR(code and doc) #4102 
  - [ ] object detection (coco, yolo3) @linbinskn  ~Sep 1~ Sep 22
    - [x] investigate model compression paper and try to compress model by NNI.
    - [x] review meeting for investigate and NNI result(demo). ~Sep 2~ Sep 8
    - [x] support multi-gpu training @chenbohua3 #4127
    - [x] support bn-folding for lsq quantizer Sep 8 #4148 
    - [ ] review meeting for comparing results. Sep 26
    - [ ] improvement and PR(code and doc)

### HPO
- [x] refactor Hyper-opt based algorithm - random tuner. @liuzhe-lz #4118

### nnictl & nnimanager & training service @SparkSnail @liuzhe-lz @acured 
- [ ] P0 - fix macos ut @liuzhe-lz ~Aug 20~ Aug 24 #4109
  - [ ] (bug bash)ut stage 2, modify dependency injection
- [x] P0 - add trial gpu test in UT, verify whether gpu is used in IT @acured #4162
- [x] P0 - hybrid local & remote & aml integration test @SparkSnail Aug 23 #4124 
- [x] P0 - clean deprecated code (nasui) @ultmaster (nasui)#4088 
- [x] P0 - demo and improve distributed trials on different training services (e.g., kubeflow) @SparkSnail Sep 8
  - [x] Is support? How to support? investigate
- [x] fix pipeline manual az login issue @acured Aug 20 #4082
- [x] fix model speedup out of memory? issue @J-shang 
- [x] experiment config doc update @J-shang #4131 
- [x] improve doc: clarify the difference between training service storage and shared storage @J-shang #4217
- [x] double check the cancel logic of aml (&pai?) trial runner @SparkSnail 

### WebUI
- [x] bug fix - Improve trial intermediate result graph. @Lijiaoa  #4171
- [x] bug fix - webui prompts error message. @Lijiaoa  #4164

### regression test needed, or bugs reported during the iteration by external users (need test and close the issues)
- [x] #4077, #4083 Restful server started failed @acured 
- [ ] nni==2.3 tensorboard uninstall then install get __version__ erro,how solve it? #4087 @SparkSnail 
- [ ] #4079 @Lijiaoa 
- [ ] Exponential Notation is not allowed anymore #4080 @QuanluZhang 
- [ ] SyntaxError on WebUI with old version of Firefox #4081 @Lijiaoa 
- [x] #4158 @acured 
- [ ] assert len(set(num_channels_list)) == 1 #4160 @J-shang 
- [ ] #4066 users found an walkaround, we need a fix for it @liuzhe-lz 
- [ ] Task is always in a waiting state in the remote machine #3905 (not an 2.4 regression but a 2.1 regression) @acured 
- [ ] NNI installation issue with ConfigSpace-0.4.7 #3909 (not sure whether this is a regression or not) @liuzhe-lz 
- [ ] Runtime Error during L1FilterPruner (and other one-shot pruners) #3944 @zheng-ningxin 
- [ ] submit task to OpenPAI cluster failed #4022 @SparkSnail 
- [ ] #3978 @SparkSnail 
- [ ] Got Segmentation fault when running amc_search.py #4000 (to check whether there are any version limits) @linbinskn 
- [ ] View an experiment with experiment path. #3953 @SparkSnail to verify and close the issue
- [ ] AutoCompress with level pruner leads to runtime error #3948 @J-shang
- [ ] SPOS hardware-aware nas multi_trial.py don't work #4198 @JiahangXu 

### delayed
  - [ ] classification @jonsnows ~Aug 26~ 
    - [x] investigate search space and common models and chose one to start.
    - [x] review meeting for investigate. Aug 30
    - [ ] implement NAS (run on openpai ne cluster). ~Sep 8~ Sep 10
    - [ ] review meeting for result(demo). ~Sep 15~ ~Sep 22~ Sep 29
    - [ ] improvement and PR(code and doc)
  - [ ] object detection @QuanluZhang ~Aug 30~ ~Sep 6~ ~Sep 8~ ~Sep 9~ ~Sep 15~
    - [x] investigate search space and common models and chose one to start.
    - [x] review meeting for investigate. Sep 16
    - [ ] implement NAS, baseline model result
    - [ ] review meeting for result(demo). 
    - [ ] improvement and PR(code and doc)

**Comment by acured** [comment]
## Stretch goals

### NAS
- [ ] P0 - Add examples for NAS-Bench-series @ultmaster 
  - [ ] P2 - 301
- [ ] P2 - Evaluate existing strategies (multi-trial) on NAS benchmarks @ultmaster 
- [ ] P0 - Support one system-level optimization: CSE optimization to deduplicate computation @hzhua pr #3202 
- [ ] P0 - *Improve training service to support CSE optimization* @hzhua #3897 
- [ ] P2 - TensorFlow support: graph converter and support inline mutation API @liuzhe-lz 
  - [ ] add raw framework
  - [ ] add example 7.12
- [ ] P0 - Migrate FBNet from NAS v1.0 to Retiarii framework @Ali 
- [ ] P2 - AutoDropout @skeletondyh 7.16
- [ ] P1 - Evaluate one-shot strategies on NAS benchmarks @ultmaster 
- [ ] P1 - Further improve the logic of graph generation and code generation (Further integrated with TorchScript) @QuanluZhang
- [ ] P1 - Test classic nas tuners on NNI NAS benchmark and report evaluation results @ultmaster 
- [ ] P2 - Migrate Cream from NAS v1.0 to Retiarii framework @ yuhangchen
- [ ] P2 - refactor of Retiarii execution engine @ultmaster 
  - [ ] support local debug mode for pure-python execution engine
  - [ ] support weight transfer from supernet to submodel
  - [ ] support export of top model for pure-python execution engine
  - [ ] P2 - refactor of "self._cur_samples" in mutators
  - [ ] P2 - support validation for other strategies
- [ ] P1 - Review strategy/experiment/rest stop condition @QuanluZhang 
- [ ] P1 - support graph-based NAS algorithms @ultmaster @skeletondyh
- [ ] P1 - Deal with strategy failure 


### Model Compression
- [ ] P0 - support iterative pruning @J-shang  6.18 review meeting (done) / 6.23 sample / 6.25 7.14
  - [ ] P0 - implement model compression 2.0, include 8 maskers (basic pruners) 7.9 #3917 
  - [ ] P0 - improve pruners to more faithfully reproduce the papers @J-shang 
  - [ ] P2 - Refactor `compress()` in IterativePruner, unify support AGP, ADMM. (#3669 )
  - [ ] P2 - Add more criteria(strategy, i.e., acc drop toleronce) (discussion needed)  
- [ ] P1 - MixedMaskerPruner @J-shang 
- [ ] P2 - Refactor of model graph generation (as an independent component) @zheng-ningxin 

### Training service & NNI manager && nnictl
- [ ] P0 - (discussion needed) design an API to share data loading/preprocessing among trials (#3294 )
  - [ ] P2 - implementation
 - [ ] P0 - Make **reuse** default @SparkSnail 
  - [ ] P1 - support storage service for different training services, review and implementation
  - [ ] P1 - add more test for remote mode training service
  - [ ] P2 - Frameworkcontroller support @SparkSnail
- [ ] P0 - fix path escape error in windows (issue #3869) @liuzhe-lz @acured @J-shang #3898
  - [ ] add back removed ut
- [ ] P2 - Mask confidential config fields (depends on prev items) @liuzhe-lz
- [ ] P2 - `nnictl experiment export` improvements @J-shang 
- [ ] P2 - internal tuner APIs for improving tuner debuggability, allow debugger tool @liuzhe-lz 
- [ ] P2 - nnictl auto-completion @liuzhe-lz 
- [ ] P2 - Dependency-aware supported in iterative pruner (discussion needed)
- [ ] P2 - Add full test (l2filter, Taylor, NetAdapt, SimulatedAnnealing, AutoCompress, AMC, Sensitivity, ADMM, Lottery Ticket)
- [ ] P1 - reuse mode: ADL kubeflow support @SparkSnail
- [ ] P2 - add/del tag of experiments (pending support from rest server)
- [ ] UI: support experiment resume/view/stop on webUI
- [ ] P0 - (discussion needed) how to support specifying initial configs (#3801 ) @ultmaster 
- [ ] P2 - (discussion needed) support constraints on hyper-parameters @ultmaster 
- [ ] P2 - handle all reject errors @J-shang 

### WebUI
- [ ] P0 - Adaptive UI (height) for high resolution, current window for high resolution need improvement @junzhuzhang  
  - [ ] overview page: blank at the bottom
  - [ ] align issue in overview page
  - [ ] support searching customized string in the search box

### Hyper-parameter tuning
- [ ] P1 - Improve HPO benchmarks, add more concrete conclusions
  - [ ] add one benchmark and one search space 7.14 #3925 
- [ ] P1 - support nested search space @kvartet 6.28 discussion meeting
- [ ] P1 - Improve hyperband, PBT with shared storage (dependency on shared storage implementation) @acured 
- [ ] P1 - upgrade cuda, config_space, docker image  @liuzhe-lz 7.21 #3976
- [ ] P1 - grid search does not support `_name` for nested search space (update doc) @kvartet 
- [ ] P1 - evolution tuner does not mutate sub search space for nested search space @kvartet 

### Pipeline
- [ ] P0 - support python 3.9 in pipeline (wait for pytorch upgrade from 1.6 to 1.9) @ultmaster #3881 
  - [ ] P2 - write ipc test
- [ ] P0 - fix and improve pipeline
  - [ ] nnimanager ut, nni-ci-gpu-03 failed, maybe due to this machine's environment, cannot be executed through daemon, need reimage -> create a new vm

**Comment by QuanluZhang** [comment]
Bugbash manager @liuzhe-lz (check other prs)

### NAS
- [ ] (need review) fix benchmark @ultmaster tester: @QuanluZhang 
  - [ ] unify architecture format. Aug 20 #4090
  - [ ] provide simple API for query. Aug 20 #4090
  - [ ] support benchmark end2end (test strategies' performance) #4205 
- [ ] support serialization @ultmaster #4172 tester: @liuzhe-lz 
- [ ] review and improve nas tests stage 1 @ultmaster. #4097 tester: @liuzhe-lz 
- [ ] improve quick start (notebook) @QuanluZhang.   #4094 tester: @ultmaster 
  - [ ] replace example, update mnist example. 
- [ ] examples for image classification, object detection, audio (show reasonably good performance) tester: @ultmaster 
  - [ ] transformer @skeletondyh #4222 
- [ ] deal with pytorch lightning onnx error for NAS visualization @ultmaster, tester: @QuanluZhang 

### Model Compression
- [ ] support compression v2 @J-shang  #3917 #4074 #4089 #4116 #4178 #4125 tester: @Fiascolsy 
  - [ ] tests 
  - [ ]  (bug bash)doc tutorial
- [ ] support per-channel quantization @linbinskn  #4137 tester: @J-shang 
- [ ] end2end examples for image classification, object detection, audio, transformer (show reasonably good performance) tester: @J-shang 
  - [ ] image classification (MobileNet) @xiaowu0162  #4102

### HPO
- [ ] refactor Hyper-opt based algorithm - random tuner. @liuzhe-lz #4118 tester: @ultmaster 

### nnictl & nnimanager & training service @SparkSnail @liuzhe-lz @acured 
- [ ] experiment config doc update @J-shang #4131 tester: @linbinskn 
- [ ] improve doc: clarify the difference between training service storage and shared storage @J-shang #4217  tester: @linbinskn 

### WebUI
- [ ] bug fix - Improve trial intermediate result graph. @Lijiaoa  #4171 tester: @SparkSnail 
- [ ] bug fix - webui prompts error message. @Lijiaoa  #4164 tester: @SparkSnail 

### regression test needed, or bugs reported during the iteration by external users (need test and close the issues)
- [x] #4077, #4083 Restful server started failed @acured 
- [ ] nni==2.3 tensorboard uninstall then install get __version__ erro,how solve it? #4087 @SparkSnail 
- [ ] #4079 @Lijiaoa 
- [ ] Exponential Notation is not allowed anymore #4080 @QuanluZhang 
- [ ] SyntaxError on WebUI with old version of Firefox #4081 @Lijiaoa 
- [x] #4158 @acured 
- [ ] assert len(set(num_channels_list)) == 1 #4160 @J-shang 
- [ ] #4066 users found an walkaround, we need a fix for it @liuzhe-lz 
- [ ] Task is always in a waiting state in the remote machine #3905 (not an 2.4 regression but a 2.1 regression) @acured 
- [ ] NNI installation issue with ConfigSpace-0.4.7 #3909 (not sure whether this is a regression or not) @liuzhe-lz 
- [ ] Runtime Error during L1FilterPruner (and other one-shot pruners) #3944 @zheng-ningxin 
- [ ] submit task to OpenPAI cluster failed #4022 @SparkSnail 
- [ ] #3978 @SparkSnail 
- [ ] Got Segmentation fault when running amc_search.py #4000 (to check whether there are any version limits) @linbinskn 
- [ ] View an experiment with experiment path. #3953 @SparkSnail to verify and close the issue
- [ ] AutoCompress with level pruner leads to runtime error #3948 @J-shang
- [ ] SPOS hardware-aware nas multi_trial.py don't work #4198 @JiahangXu
