### ISSUE TITLE
NNI v2.8 Iteration Plan

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/nni#4735]
# Release Plan for vNext release
- Release manager: @QuanluZhang 
- Release start date: tbd
- Feature freeze date: 5.11
- Code freeze and demo date: ~5.18~ 5.20
- Branch cut and next release planning date: tbd
- Bugbash: ~6.1~ ~6.10~ 6.13
- Release date: ~6.13~ ~6.17~ 6.20

# Planned Items
## NAS 
owners: @ultmaster / @QuanluZhang / @JiahangXu / @hzhua
- [x] P0 Merge [dev-oneshot](https://github.com/microsoft/nni/tree/dev-oneshot) back to master. #4760 @ultmaster
- [x] P0 type hint 4.22 #4774 @ultmaster
- [x] P0 [Doc] translation framework document #4759 @ultmaster
- [ ] P0 NAS experiment @QuanluZhang 
  - [ ] adopt Zhe's refactor on experiment ~4.29~ ~5.6~ 5.10 #4841 
- [x] P0 type hint for one-shot 4.30 #4811 @ultmaster
- [x] P0 Test correctness of final architecture in search space hub. 5.5 @ultmaster #4831 
- [x] P1 CGO supports pytorch-lightning 1.6 @hzhua  #4814 
- [ ] P1 Multi-GPU support for one-shot NAS. #4603 （external contributor: @Frandium)
- [ ] P1 one-shot supports repeat and cell API #4835 

## Pipeline
- [x] P1 Setup full tests with [scale-set agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops). @ultmaster 
  - [x] placeholder #4846 
  - [x] vmss for windows
- [ ] P0 replace docker hub @liuzhe-lz 

## HPO
owner: @liuzhe-lz 

- [x] P1 - Make `config.tuner.name` case insensitive and let it accept advisors (1 day)
  - #4773 
- [x] P1 - Fix TPE import for old metrics
  - #4804
  - #4865
- [x] Fix TPE nested search space
  - #4810
  - #4866
- [x] Fix `merge_parameter()`
  - #4837
  - #4868

## Experiment
owner: @liuzhe-lz 

- [x] P0 - Fix Python logging  (~1 week, ~~waiting discussing~~) 4.26
  - #4499
  - [x] #4792 
- [x] Refactor NNI manager globals
  - [x] #4703
  - [x] #4705
  - [x] #4706
  - [ ] **Check** it provides proper message when initializing fails due to remote nni-experiments IO
- [x] Migrate dispatcher IPC to WebSocket (~~depends on global shutdown~~)
  - ~~#4660~~
  - [x] #4806
  - [x] #4808
  - [x] #4821
  - [x] #4825
- [x] Support multiple HPO experiments in one process
  - #4855
- Deferred - ~~Fix experiment management file lock~~ (5 days)
  - [x]  #4824
- [x] P1 - Use launcher's `sys.executable` to detect Python interpreter. Don't blindly use `python3`.
  - #4799
  - #4840
- Deferred - ~~Support non-English file name~~
  - #4805 

## WebUI
owner: @Lijiaoa 
- [x] kill job component(code refactor) #4772 
    - [x] fix detail page update issue
    - [x] refactor kill job
- [x] P0 log component(code refactor) (Zhe for the help) 4.21 #4794 
- [x] P0 support searching customized string in the search box 4.28 #4823 
- [x] P1 design discussion, hyper-parameter ordering on webui
- [x] P1 Hyper-parameter overview top trials order
  - #4839
  - #4856

## Compression
owners: @J-shang /@zheng-ningxin 
- [ ] P0 add a tutorial for config list ~5.10~  
- [ ] P0 nni auto compress experiment @J-shang
  - [x] design review 4.20
  - [ ] first version implementation ~4.27~ 4.29 #4836 
- [x] P0 type hint 4.26 #4800 @J-shang
- [x] P0 support RecursiveScriptModule in speedup #4801 @J-shang
- [ ] P1 support block sparse in level pruner #4812 @J-shang
- [x] P1 support customization of module replacement function in model speedup (refer to the interface of super-kernel) @zheng-ningxin 5.4 #4826 

## Deferred
- [ ] P3 - step 6 - global REST handler register (depends on WebSocket and experiment management refactor)
- [ ] P1 pruning config list extension @J-shang
  - [ ] design review ~4.22~
- [ ] P0 Tutorial for one-shot NAS. (depends on 4760) #4509 @ultmaster  @JiahangXu ~4.27~ ~5.6~ ??
- [ ] strategies respect resource constraints

**Comment by matluster** [comment]
### NAS

* Merge [dev-oneshot](https://github.com/microsoft/nni/tree/dev-oneshot) back to master.
* Multi-GPU support for one-shot NAS. #4603 
* Test correctness of final architecture in search space hub.
* Test support of one-shot strategies to search space hub.

### Pipelines

* Isolate framework tests from algorithm tests.
* Setup full tests with [scale-set agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops).

**Comment by liuzhe-lz** [comment]
## HPO ##

- [ ] Make `config.tuner.name` case insensitive and let it accept advisors

## Experiment ##

- [ ] Refactor NNI manager globals (PR: #4703 #4705 #4706 )
- [ ] Migrate dispatcher IPC to WebSocket (PR: #4497 )
- [ ] Fix Python logging (Issue: #4499 )
- [ ] Fix experiment management file lock

**Comment by J-shang** [comment]
### Compression
- [ ] pruning config list extension
- [ ] nni auto compress experiment
- [ ] quantization framework refactor
- [ ] Net Adapt Pruner
- [ ] FLOPs counter supports masks

**Comment by QuanluZhang** [comment]
bugbash:

## NAS 
- [ ] P0 Merge [dev-oneshot](https://github.com/microsoft/nni/tree/dev-oneshot) back to master. #4760 @ultmaster tester: @QuanluZhang 
- [ ] P0 NAS experiment @QuanluZhang tester: @ultmaster 
  - [ ] adopt Zhe's refactor on experiment ~4.29~ ~5.6~ 5.10 #4841 
- [ ] P0 Test correctness of final architecture in search space hub. 5.5 @ultmaster #4831 teser: @QuanluZhang 
- [ ] P1 CGO supports pytorch-lightning 1.6 @hzhua  #4814 tester: @QuanluZhang 
- [ ] P1 Multi-GPU support for one-shot NAS. #4603 （external contributor: @Frandium) tester: @QuanluZhang 
- [ ] P1 one-shot supports repeat and cell API #4835 tester: @QuanluZhang 

## HPO
owner: @liuzhe-lz tester: @J-shang 

- [ ] P1 - Make `config.tuner.name` case insensitive and let it accept advisors (1 day)
  - #4773 
- [ ] P1 - Fix TPE import for old metrics
  - #4804
  - #4865
- [ ] Fix TPE nested search space
  - #4810
  - #4866
- [ ] Fix `merge_parameter()`
  - #4837
  - #4868

## Experiment
owner: @liuzhe-lz 

- [ ] P0 - Fix Python logging  (~1 week, ~~waiting discussing~~) 4.26 tester: @ultmaster 
  - [ ] #4499
  - [ ] #4792 
- [ ] Support multiple HPO experiments in one process tester: @J-shang 
  - #4855
- [ ] P1 - Use launcher's `sys.executable` to detect Python interpreter. Don't blindly use `python3`. tester: @yuhuixii
  - #4799
  - #4840

## WebUI
owner: @Lijiaoa tester: @liuzhe-lz 
- [ ] kill job component(code refactor) #4772 
    - [ ] fix detail page update issue
    - [ ] refactor kill job
- [ ] P0 log component(code refactor) (Zhe for the help) 4.21 #4794 
- [ ] P0 support searching customized string in the search box 4.28 #4823 
- [ ] P1 design discussion, hyper-parameter ordering on webui
- [ ] P1 Hyper-parameter overview top trials order
  - #4839
  - #4856

## Compression
owners: @J-shang /@zheng-ningxin 
- [ ] P0 nni auto compress experiment @J-shang tester: @liuzhe-lz 
  - [ ] first version implementation ~4.27~ 4.29 #4836 
- [ ] P0 support RecursiveScriptModule in speedup #4801 @J-shang tester: @zheng-ningxin 
- [ ] P1 support customization of module replacement function in model speedup (refer to the interface of super-kernel) @zheng-ningxin 5.4 #4826 tester: @J-shang 

More prs:
TBD

**Comment by matluster** [comment]
Logging:

* All logs appear twice in console.
* Logs on console doesn't have logger name. Expected?

<img width="816" alt="image" src="https://user-images.githubusercontent.com/79736092/171302447-22a56882-f4f0-4d60-a77c-85c345590841.png">

NAS experiment: hang in this state. Experiment status is DONE.

<img width="492" alt="image" src="https://user-images.githubusercontent.com/79736092/171303318-707711d9-2ef6-4417-88e4-aa2feec54ed0.png">

When I press Ctrl-C, the traceback is:

```python
^CException ignored in: <module 'threading' from '/home/azureuser/miniconda3/envs/nni/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/home/azureuser/miniconda3/envs/nni/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
[2022-06-01 00:09:19] Stopping experiment, please wait...
INFO:nni.retiarii.experiment.pytorch:Stopping experiment, please wait...
[2022-06-01 00:09:19] Dispatcher exiting...
INFO:nni.runtime.msg_dispatcher_base:Dispatcher exiting...
[2022-06-01 00:09:20] Dispatcher terminiated
INFO:nni.runtime.msg_dispatcher_base:Dispatcher terminiated
[2022-06-01 00:09:20] Experiment stopped
INFO:nni.retiarii.experiment.pytorch:Experiment stopped
```

**Comment by J-shang** [comment]
WebUI:
- optimization curve, min/max
- search need an enter button
- download trials info csv, json
