### ISSUE TITLE
Iteration Plan for April 2019

### ISSUE THREAD

**Issue by scarlett2018** [Microsoft/nni#944]
_This plan is still in draft status._

This plan captures our work in **April**. This is a 4 week iteration, and we will **ship** our April update in **in early May**. We'll continue work we started in the previous iteration, and we started to pick up items from our [roadmap](https://github.com/Microsoft/nni/wiki/Roadmap).

## Endgame
**April 19**: Code freeze for the endgame
**April 26**: Endgame done

The endgame details for this iteration are tracked in [April Endgame](https://github.com/Microsoft/nni/issues/963).

## Plan Items
Below is a summary of the top level plan items.

### New OS Support
- [x] 1. Support NNI on Windows #875 @demianzhang

### Tuners and Assessors
- [x] 1. New Tuner: BOHB. #844 @PurityFan 
- [x] 2. Assessor knows trials’ status (successful/failed), does tuner also have this requirement? #857 @Crysple 
- [x] 3. Ability to resume a tuner #879 @QuanluZhang @Crysple @PurityFan 

### Training Service
- [x] 1. Provide better error message on irregular configuration file formats failures #896 @SparkSnail 
- [x] 2. Designated gpu devices for NNI trial jobs #775 @chicm-ms 

### Web Portal & User Experience
- [x] 1. Ability to generate analysis results report after the experiement execution #880 @leckie-chn 
- [x] 2. Decimal format of metrics other than default on the Web UI #894 @lvybriage 
- [x] 3. There are not hints in WebUI about Multi-phase #926 @lvybriage 
- [x] 4. Enable copy/paste for hyperparameters as python dict (将超参数以python字典的形式到剪贴板) #904 @lvybriage @yangou1988 @ymlgithub
- [x] 5. Enable ealy stopped trials data for tuners. #843 @chicm-ms @lvybriage 

### Bug Fixes 
- [x] 1. Unable to kill all python threads after `nnictl stop` in async dispatcher mode #501 @QuanluZhang 
- [x] 2. `nnictl --version` does not work with `make dev-install` #709 @Crysple 

### Engineering Improvements
- [x] 1. All trail jobs status stays on 'waiting' for long time on PAI platform #592 @chicm-ms 
- [x] 2. Refactor dispatcher / trial job log settings #920 @chicm-ms 

### Docs, Blogs, Samples, Articals
- [x] 1. Multiphase doc should be more clear on scenarios. #659 @QuanluZhang 
- [ ] 2. add an example for Recommenders #957 @Crysple  
-----------------------
## Pending Items
- [ ] 1. Adopt PAI Mid-April release REST API breaking change #941 @yds05 

-----------------------
## Deferred Items
- [ ] 1. Show PAI job link in NNI trial section. #837 @yds05
